export const CREATE_HOUSE ='create_house';
export const CREATE_ROOM = 'create_room';
export const CREATE_ERROR ='create_error';
export const UPLOAD_IMAGE = 'upload_image';
export const GET_HOUSES = 'get_houses';
export const GET_ROOMS = 'get_rooms';
export const GET_ERROR = 'get_error';
export const CURRENT_TAB = 'current_tab';
export const SET_HOUSE_DETAILS_ID = 'set_house_details_id';